import type { Metadata } from "next";
import { Urbanist, Figtree } from "next/font/google";

import Header from "@/features/Layout/Header";

import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // customize as needed
  variable: "--font-urbanist",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // customize as needed
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body
        className={`${urbanist.variable} ${figtree.variable} font-urbanist min-h-screen bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
